baseURL: "https://jrgn.me"
title: jrgn
copyright: "My content is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) - jrgn, 2024"
paginate: 5
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: jrgn
  description: "jrgn's homepage and blog"
  author: "Jørgen Skontorp"
  images: ["images/jrgn-cover-dark.png"]
  # DateFormat: 
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  mainSections: # choose what to be visible on home page
    - blog
    - weird

  summaryLength: 70  # Default is 70 words. This is overwritten by more delimiter and front matter
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false # To have the toc open by default and not collapsed
  #displayFullLangName: true
  ShowAllPagesInArchive: true
  ShowPageNums: true

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
  #     Favicon link if its not in static:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # To change name and icon in upper left corner
  #label:
  #  text: "jrgn"
  #  iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  #  icon: /apple-touch-icon.png
  #  iconHeight: 35

  # profile mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: jrgn
    imageUrl: "/images/profile.png"
    imageTitle: "Profile picture of me, in the style of Van Gogh"
    imageWidth: 250
    imageHeight: 250
    subtitle: "hi, how are you?"
    #buttons:
    #  - name: Archives
    #    url: archives
    #  - name: Tags
    #    url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      title: My GitHub profile
      url: "https://github.com/jrgn9"
    - name: linkedin
      title: My LinkedIn profile
      url: "https://linkedin.com/in/jrgn9"
    - name: email
      title: Contact me
      url: "mailto:hello@jrgn.me"

  #analytics:
  #  google:
  #    SiteVerificationTag: "XYZabc"
  #  bing:
  #    SiteVerificationTag: "XYZabc"
  #  yandex:
  #    SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page
    responsiveImages: false # false to reduce generation time and size
    linkFullImages: false # enable: hyperlinks to the full image size on post pages

  #editPost:
  #  URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link
  
  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 20 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content", "description", "tags"]

menu:
  main:
    - identifier: about
      name: about me
      url: about/
      weight: 1
    - identifier: blog
      name: blog
      url: blog/
      weight: 2
    - identifier: weird
      name: keep the internet weird
      url: weird/
      weight: 3
    - identifier: search
      name: search
      url: search/
      weight: 4

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
   vimeo:
     disabled: false
     simple: true

   twitter:
     disabled: false
     enableDNT: true
     simple: true

   instagram:
     disabled: false
     simple: true

   youtube:
     disabled: false
     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
