baseURL = 'https://jrgn.me'
title = 'jrgn'
author = 'Jørgen Skontorp'
copyright = 'jrgn, 2024'
theme = 'risotto-0.4.0'
languageCode = 'en-us'
DefaultContentLanguage = "en"
contentDir = 'content'
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
enableEmoji = true

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "gruvbox-light"

# Sidebar: about/bio
[params.about]
title = "jrgn"
description = "yes? no? maybe? I don't know? can you repeat the question?"
logo_image = "/images/profile.png"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/jrgn9"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/jrgn9"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "weird"
    name = "Keep the Internet Weird"
    url = "/weird/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# More settings here: https://github.com/joeroe/risotto/blob/main/exampleSite/config.toml
