name: Build and Deploy Hugo site

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.128.0
        TARGET_REPO: jrgn9/jrgn.me
        TOKEN: ${{ secrets.TOKEN }}
        CNAME: www.jrgn.me

